sudo: required
services:
  - docker

before_install:
  - docker build -t chenyunshu2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run chenyunshu2/react-test npm test -- --coverage

after_success:
  - docker build -t chenyunshu2/multi-client ./client
  - docker build -t chenyunshu2/multi-nginx ./nginx
  - docker build -t chenyunshu2/multi-server ./server
  - docker build -t chenyunshu2/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-nginx
  - docker push stephengrider/multi-server
  - docker push stephengrider/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-051731902500"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
