sudo: required
services:
  - docker

before_install:
  - docker build -t chenyunshu2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chenyunshu2/docker-react npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-051731902500"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
